### ISSUE TITLE
Passing dynamic object not working

### ISSUE THREAD

**Issue by nickle72000** [zerodevx/svelte-json-view#1]
Writen below code using this as child component. getting error as "<JsonView> was created with unknown prop 'app'"

<script>
    import { JsonView } from '@zerodevx/svelte-json-view';
    
   export let data;
   
   const app = data;
   
console.log(app.trace);

</script>

<JsonView {app} />

**Comment by zerodevx** [comment]
The prop name is `json`. So:

```html
<JsonView json={app} />
```

**Comment by zerodevx** [comment]
Marking as solved. Feel free to reopen if there are issues.
