### ISSUE TITLE
[Suggestion] Documentation on API for changing state

### ISSUE THREAD

**Issue by danielimmke** [zerodevx/svelte-json-view#4]
Great package! Super easy to use.

The only thing is, there isn't any documentation on an API for the buttons you are using in your demo link. I think it would be helpful to add that. Unless those buttons are not part of the package and you're simply transforming the JSON and it's being reflected.

I am digging through the code trying to find and might submit a PR updating the docs if I do.

**Comment by danielimmke** [comment]
So it seems like indentation is handled with the `depth` property and the other stuff is mostly presentational.

It may be beyond the scope of this project to add functions to directly modify the JSON. I was able to write my own "copy" button in 5 minutes, but the same might not be true for everyone, so it might be an easy add? I don't know. Here's what I did (had SSR turned off on this page so didn't have to check for client side.)

Either way, thanks for making this package!

```ts
  const copyJSON = async () => {
    const blob = new Blob([JSON.stringify(json)], { type: "text/plain" });

    await navigator.clipboard.write([
      new ClipboardItem({
        [blob.type]: blob,
      }),
    ]);
  }
````

**Comment by zerodevx** [comment]
Hey, thanks for your note. This package basically just renders the tree-view. Styles like colours and indentation can be edited using the exposed CSS vars. In the demo, other features were added but they're probably outside the scope of this package. The demo project is open-sourced here: https://github.com/zerodevx/json-pretty-print, so you can look at the implementation too.
