### ISSUE TITLE
Separate colors for braces and brackets

### ISSUE THREAD

**Issue by mavam** [zerodevx/svelte-json-view#5]
Would it be possible to make colors for braces and brackets separately configurable? Arrays and objects are quite different, and we have a use case where we want to make it visually clearer.

**Comment by zerodevx** [comment]
Not without updating the code I'm afraid. I'll add support.

**Comment by zerodevx** [comment]
Hey! It's now possible from `v1.0.6` like so:

```html
<div class="wrap">
  <JsonView {json} />
</div>

<style>
  .wrap {
    --jsonBracketColor: blue; /* curly brackets */
  }
  .wrap :global(.isArray) {
    color: red; /* square brackets */
  }
</style>
```

**Comment by mavam** [comment]
Awesome, thanks a bunch! 🙏
