### ISSUE TITLE
--jsonPaddingLeft doesn't seem to be working?

### ISSUE THREAD

**Issue by rossdanlm** [zerodevx/svelte-json-view#7]
Hey! I tried following the README and using `--jsonPaddingLeft` but it doesn't seem to have any affect. I got `--jsonBorderLeft` to work but that's not exactly what I want
```svelte
<div class="myJsonWrapper">
  <JsonView json={my_data} />
</div>

<style>
  .myJsonWrapper {
    --jsonPaddingLeft: 10px;
    /* --jsonBorderLeft: 10px dotted white; */
  }
</style>
```

What it normally looks like (and still can't get it to work)
<img width="362" alt="Screenshot 2024-01-09 at 17 52 47" src="https://github.com/zerodevx/svelte-json-view/assets/151060367/0e67d6c3-ccfa-45f2-9ba4-d35474cc7c4f">

What it looks like if I add `--jsonBorderLeft`:
<img width="355" alt="Screenshot 2024-01-09 at 17 53 11" src="https://github.com/zerodevx/svelte-json-view/assets/151060367/78bf0e13-73fb-45af-828f-c016eaa52c2a">

**Comment by zerodevx** [comment]
Internally, the component renders the JSON tree as `<ul><li>...</li></ul>` nodes, so it's likely you've stylesheets applied globally that's bleeding into the component.

Quick fix is to reset these styles onto your wrapper class.

```html
<style>
  .myJsonWrapper {
    list-style-type: none;
    --jsonPaddingLeft: 10px;
    /* --jsonBorderLeft: 10px dotted white; */
  }
</style>
```

**Comment by rossdanlm** [comment]
Thanks, that fixed the issue!

**Comment by snowe2010** [comment]
this didn't work for me. I eventually just did `--jsonBorderLeft: 10px dotted transparent;` which 'tabbed' it properly
