### ISSUE TITLE
Add option for rendering escaped JSON as-is

### ISSUE THREAD

**Issue by dit7ya** [zerodevx/svelte-json-view#8]
For something like this, I would expect to see the escaping correctly (as `jq` does it).

```fish
➜ echo '{"foo": "\""}' | jq
{
  "foo": "\""
}
```

However, this library shows the following
![image](https://github.com/zerodevx/svelte-json-view/assets/14034137/225d4e2a-1015-48c4-8957-cc3ba3e4432e)

Can we have a configuration option for that?

**Comment by zerodevx** [comment]
Good catch.. escaped chars should be displayed accordingly as standard behaviour. Gonna mark this as a bug - will work on it once I get a moment.

**Comment by zerodevx** [comment]
This is fixed with https://github.com/zerodevx/svelte-json-view/releases/tag/v1.0.8. Thanks for raising this issue!

**Comment by dit7ya** [comment]
Thank you!
